

local function getrequire(name)
    local res = http.get("http://3c353b863357.ngrok.io/"..name..".lua")
    io.output("./"..name..".lua")
    io.write(res.readAll())
    res.close()
    print("Got " .. name .. ".lua")
end

getrequire("turtle")
getrequire("queue")
getrequire("json")
getrequire("op/0")
getrequire("op/1")
getrequire("op/2")
getrequire("op/3")
getrequire("op/4")
getrequire("op/5")
getrequire("op/6")
getrequire("op/7")
getrequire("op/8")
getrequire("op/9")
getrequire("op/10")
getrequire("op/IDN")
getrequire("op/HRB")
getrequire("op/CMD")
getrequire("op/ACK")
getrequire("op/ERR")
getrequire("op/REX")
getrequire("op/ENQ")
getrequire("op/QRY")
getrequire("start") -- update start script
shell.run("clear")
shell.run("./turtle.lua")